### ISSUE TITLE
Examples: Cannot POST on http://localhost:4000/admin/validate

### ISSUE THREAD

**Issue by davd33** [senecajs/seneca-web#125]
I get the following error trying to send a POST request on `http://localhost:4000/admin/validate`:

>{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}

I tried with: `using_express.js`, `using_hapi.js` and `using_connect.js`, but no success.
The other routes work: `/todo/list` and `/todo/edit`.

**Comment by tswaters** [comment]
The command is `validate` but the alias is set to `/manage` so it must be accessed via:  `POST http://localhost:4000/admin/manage`

**Comment by davd33** [comment]
It does not work.
I try to send a POST with this script: https://gist.github.com/davd33/c65e5829d048c089dc8d7a405b83a7ad

And run the command:
> using_url=http://davd33-laptop:4000 node send_post.js

I get the following output:
> get on: http://davd33-laptop:4000/todo/list
{"ok":true}
post on: http://davd33-laptop:4000/admin/manage
{"statusCode":404,"error":"Not Found","message":"Not Found"}

**Comment by tswaters** [comment]
I'm at work at the moment and will take a closer look at this either tonight or tomorrow sometime.

**Comment by tswaters** [comment]
Apologies for the inaccurate information above. With the current setup in `./docs/examples/common/routes.js`, it should be `POST /manage`... reason being, when `alias` is in play, [it overwrites everything](https://github.com/senecajs/seneca-web/blob/2.0.0/lib/mapper.js#L96-L98).  The `name` option can be used to overwrite the part component of the url.

If you want:
- `POST /admin/validate`, remove `alias`
- `POST /admin/manage` replace `alias: '/validate'` with `name: '/manage'`

And actually, the slashes here are redundant because everything is run through `path.join` so it could just be `alias: 'validate'` or `name: 'manage'`

It might be valuable to add a loglevel option that can tie into some `seneca.log` entries in the adapters, so they output what is actually being bound to the web application.... this would be invaluable for debugging and figuring out what is actually going on.

**Comment by davd33** [comment]
Thank you :+1: for your answer, I understand now how it works for the alias part.

However I struggle to **make the `suffix` option work**.
I forked seneca web and created a new route to show what I mean.
A `send_post.js` script sends requests to the server as shown in my previous post.

Do I do something wrong to make it work?

Forked repo: [here](https://github.com/davd33/seneca-web).

**Comment by tswaters** [comment]
I've send a PR for your fork that fixes the issue.... https://github.com/davd33/seneca-web/pull/1/files.  The path as you have it is created properly as  `/todo/test/:name`

When `:name` exists in the path you need to include a param there otherwise express won't match it.  I updated the post to be to `/todo/test/davd` instead of just `/todo/test`

You can include post data of `name` here, but the route doesn't have any handling of `req.body` so it's pointless.  However, to get JSON back out from request you need to pass `json:true` to the options.

**Comment by tswaters** [comment]
Closing old tickets that should be resolved now.
