### ISSUE TITLE
add support for chairo

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-web#20]
this needs to be built in, so you can say:

```js
var Hapi = require('hapi')
var server = Hapi.Server()
server.register( seneca.export('hapi') )
```

(consider this form just a suggestion - integration mode needs more thought)

[Trello Card](https://trello.com/c/iWkIN3GC/65-seneca-web-add-support-for-chairo)

**Comment by mirceaalexandru** [comment]
@geek & @rjrodger 

This issue is fixed by:

https://github.com/hapijs/chairo/pull/32
and
https://github.com/senecajs/seneca-web/pull/38

Chairo tests are not working because it is using an export that is not published in seneca-web.
First we should merge and publish seneca-web and I will be able to add more tests to Chairo.

So these modules depends one on another we should publish them both.

Please take a look and comment.

**Comment by mirceaalexandru** [comment]
Using Hapi example:

var Chairo = require ( 'chairo' )
const Hapi = require ( 'hapi' )

var server = new Hapi.Server ()
server.connection()

server.register(
  {
    register: Chairo,
    options: {
      // options for Seneca
    }
  }, function ( err ) {
    var seneca = server.seneca

    seneca.add('role:api,cmd:qaz',function(args,done){
      done(null,{qaz:'z'})
    })

    seneca.act('role:web',{use:{
      prefix: '/api',
      pin: {role:'api',cmd:'*'},
      map:{
        qaz: {GET:true,POST:true} // accepting both GETs and POSTs
      }
    }})
  }
} )

**Comment by mcdonnelldean** [comment]
Done by @mirceaalexandru
