### ISSUE TITLE
this can support koa2?

### ISSUE THREAD

**Issue by arden** [senecajs/seneca-web#80]
this can support koa2?

**Comment by mcdonnelldean** [comment]
@arden There is a new version launching very soon that will have an easier adapter system. While Koa is not a built in adapter we would be more than happy to accept a pull request for a KOA adapter (we just had no time to build it). Watch for 1.0 launch tonight or tomorrow. The new adapter system is much easier to work with.

**Comment by mcdonnelldean** [comment]
@arden The new version is now on master, please take a look. Koa support is not included but could be easily added (no time on my end).

**Comment by tswaters** [comment]
I was going to look into this but I don't think this can be realistically included in this module.

The way things are now, [each adapter is required](https://github.com/senecajs/seneca-web/blob/master/web.js#L3-L6) when requiring `seneca-web`....  koa is a bit special due to v1 requiring generators and v2 requiring async/await.   

Building a plugin for either of these will require syntax that may not be available in the execution context and could result in a syntax error for users requiring seneca-web.

It is possible to provide an adapter like this:

```js
seneca.use(SenecaWeb, {
  adapter: require('my-koa-seneca-adapter')
})
```

I'd almost think it makes sense to split off the current adapters into separate modules (i.e., `seneca-web-express-adapter`, `seneca-web-connect-adapter`, `seneca-web-hapi-adapter`).

Support passing a string as `adapter` for backwards compatibility, but deprecate in favour of requiring the adapter directly.  At that point, adding one for koa v1 or v2 would be optional for the end-user.

**Comment by tswaters** [comment]
I've created a plugin for koa1:

https://github.com/tswaters/seneca-web-adapter-koa1

I'll do one for koa2 when I get a chance.

**Comment by tswaters** [comment]
and here's one for koa2:

https://github.com/tswaters/seneca-web-adapter-koa2

**Comment by mcdonnelldean** [comment]
Closing as Koa/2 is now supported.
